# You can use this file to create a conda environment for the bedtools module:
#   conda env create -f environment.yml
name: nfcore-bedtools-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## bioconda packages, see above
  - bedtools=2.28.0
