# This file creates a conda environment for the racon module
#   conda env create -f environment.yml
name: nfcore-module-racon
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Module-specific packages
  - racon=1.4.13
