# This file creates a conda environment for the get_crosslinks module
#   conda env create -f environment.yml
name: nfcore-getcrosslinks-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## bioconda packages, see above
  - bedtools=2.28.0