# This file creates a conda environment for the STAR module
# conda env create -f environment.yml
name: luslab-nf-star
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - star=2.7.5b
  - samtools=1.9
  - pigz=2.3.4