# This file creates a conda environment for the SEACR module
#   conda env create -f environment.yml
name: nfcore-module-seacr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - seacr=1.3
  - r-base=4.0.2