# You can use this file to create a conda environment for the nf-core peka module:
#   conda env create -f environment.yml
name: nfcore-peka-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## peka dependencies
  - matplotlib=3.1.1
  - numpy=1.17.4
  - pybedtools=0.8.0
  - scipy=1.3.1
  - seaborn=0.9.0
  - plumbum=1.6.8
  - scikit-learn=0.21.3