# This file creates a conda environment for the minimap2 module
#   conda env create -f environment.yml
name: nfcore-module-minimap2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2