# This file creates a conda environment for the fastqc module
#   conda env create -f environment.yml
name: nfcore-fastqc-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## bioconda packages, see above
  - fastqc=0.11.8