# This file creates a conda environment for the cutadapt module
#   conda env create -f environment.yml
name: nfcore-module-cutadapt
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt=2.6
