# This file creates a conda environment for the flye module
#   conda env create -f environment.yml
name: nfcore-module-flye
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Module-specific packages
  - flye=2.7
