name: docker-linting
#https://github.com/hadolint/hadolint

on:
  pull_request:
    branches: [ master ]

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          docker-name: ['Dockerfile']
          module-name: ['flye','get_crosslinks','get_crosslinks_coverage','icount','paraclu','peka','samtools','star','umi_tools','seqtk','bowtie2','minionqc','tantan']
          include:
            - docker-name: 'Dockerfile.cpu'
              module-name: 'guppy'
            - docker-name: 'Dockerfile.gpu'
              module-name: 'guppy'
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: tools/${{matrix.module-name}}/${{matrix.docker-name}}
