name: docker-build-push

on:
  push:
    branches: [ master ]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            tag: ['latest']
            docker-file: ['Dockerfile']
            module-name: ['hisat2','flye','get_crosslinks','get_crosslinks_coverage','icount','paraclu','peka','samtools','star','umi_tools','seqtk','bowtie2','minionqc','minimap2','tantan', 'star']
            include:
              - tag: 'cpu'
                docker-file: 'Dockerfile.cpu'
                module-name: 'guppy'
              - tag: 'gpu'
                docker-file: 'Dockerfile.gpu'
                module-name: 'guppy'
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luslab/nf-modules-${{matrix.module-name}}
          path: tools/${{matrix.module-name}}
          dockerfile: tools/${{matrix.module-name}}/${{matrix.docker-file}}
          tags:  ${{matrix.tag}}