name: linting

on:
    pull_request:
      branches: [ master ]
    push:
      branches: [ workflow-testing ]

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          #nxf_ver: ['20.01.0', '']
          module-name: ['bedtools','cutadapt','fastqc','get_crosslinks','get_crosslinks_coverage','icount','paraclu','peka','samtools','umi_tools']
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: tools/${{matrix.module-name}}/Dockerfile