name: workflow-testing-push

# Only runs on pushes to workflow-testing
on:
  push:
    branches: [ workflow-testing ]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luslab/nf-modules-bedtools
          dockerfile: tools/bedtools/Dockerfile
          tags: workflow-testing