name: module-testing

on:
#  push:
#    branches: [ feat-model-module ]
  pull_request:
    branches: [ master ]

jobs:
  test-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.07.1','']
        tag: ['latest']
        docker-name: ['Dockerfile']
        module-name: ['star']
        # 'htseq','velocyto','flye','homer','umi_tools','fastqc','cutadapt','bedtools','samtools', 'get_crosslinks','get_crosslinks_coverage','icount','minimap2','seqtk','paraclu','luslab_genome_tools', 'luslab_file_tools', 'bowtie2', 'metadata','minionqc', 'tantan', 'hisat2',
        include:
          - nxf_ver: '20.07.1'
            tag: 'cpu'
            docker-name: 'Dockerfile.cpu'
            module-name: 'guppy'
          - nxf_ver: ''
            tag: 'cpu'
            docker-name: 'Dockerfile.cpu'
            module-name: 'guppy'
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          export NXF_VER=${{matrix.nxf_ver}}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/ 
      - name: Docker build
        run: |
           test -f tools/${{matrix.module-name}}/${{matrix.docker-name}} && export DOCKER_EXISTS=true || echo "Dockerfile does not exist, skipping step"
           if [ -v DOCKER_EXISTS ]; then docker build -f tools/${{matrix.module-name}}/${{matrix.docker-name}} -t luslab/nf-modules-${{matrix.module-name}}:${{matrix.tag}} tools/${{matrix.module-name}}; fi
      - name: Module testing
        run: |
          nextflow run ${GITHUB_WORKSPACE}/tools/${{matrix.module-name}}/test/main.nf 